version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bookstagram-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=${MONGO_URI} 
      - SECRET=${SECRET}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: bookstagram-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    restart: unless-stopped
